### ISSUE TITLE
Your demo works until it doesn't

### ISSUE THREAD

**Issue by TomasStolp** [kriskuiper/progressive-web-apps-1920#5]
Your demo works, images get loaded, then your console explodes with image errors and they dissapear again. Then your page doesn't work on refresh and later it randomly does again.

I can't provide you screenshots or details at this point, but there might still be something wrong. 

Just reporting it.

**Comment by kriskuiper** [comment]
This is due to the serviceWorker

**Comment by kriskuiper** [comment]
It really was the service worker, fixed it now
